a=int(input("Enter the runs scored by first batsman"))
b=int(input("Enter the runs scored by second batsman"))
c=int(input("Enter the runs scored by third batsman"))
print("Strike rate of first batsman is ",a/60*100)
print("Runs first batsman would have scored if he played 60 more balls are ",2*a)
print("Maximum No. of sixes hit by him is ",int(a/6))
print("Strike rate of second batsman is ",b/60*100)
print("Maximum No. of sixes hit by him is ",int(b/6))
print("Runs second batsman would have scored if he played 60 more balls are ",2*b)
print("Strike rate of third batsman is ",c/60*100)
print("Runs third batsman would have scored if he played 60 more balls are ",2*c)
print("Maximum No. of sixes hit by him is ",int(c/6))